services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: laravel-app
    container_name: laravel-app
    ports:
      - 8000:8000
    volumes:
      - .:/var/www/html
    depends_on:
      - postgres
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: laravel

  postgres:
    image: postgres:14-alpine
    container_name: postgres-laravel
    restart: always
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: laravel
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

